<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ModelRegistry"
    nsURI="http://synthesis.ipi.ac.ru/modelregistry" nsPrefix="org.ipiran.unifier">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Rational Unified Process uses the &quot;Logical View in Rose&quot; to organize the Design Model  and the Process View and the optional Business Object Model and Analysis Model."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="RegistrationCard" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnificationReg" eSuperTypes="#//RegistrationCard">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//File"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//File"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="similarities" eType="#//File"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" eType="#//File"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationS2T" eType="#//File"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationT2S" eType="#//File"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="samples" upperBound="-1"
        eType="#//SampleReg" containment="true" eOpposite="#//SampleReg/unificationReg"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isVerified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gluing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proof" eType="#//File"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelReg" eSuperTypes="#//RegistrationCard">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractSyntax" eType="#//File"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concreteSyntax" eType="#//File"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="syntax" upperBound="-1"
        eType="#//Document" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semantics" upperBound="-1"
        eType="#//Document" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticMapping" eType="#//File"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticTransformation"
        eType="#//File" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticSpec" eType="#//File"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedBy" upperBound="-1"
        eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SampleReg" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isVerified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unificationReg" lowerBound="1"
        eType="#//UnificationReg" eOpposite="#//UnificationReg/samples"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefinementSampleReg" eSuperTypes="#//SampleReg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="concreteSourceSpec" eType="#//File"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractSourceSpec" eType="#//File"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concreteTargetSpec" eType="#//File"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractTargetSpec" eType="#//File"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceSemSpec" upperBound="-1"
        eType="#//File" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetSemSpec" upperBound="-1"
        eType="#//File" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gluing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proof" eType="#//File"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntailmentSampleReg" eSuperTypes="#//SampleReg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceConclusionConcreteSpec"
        eType="#//File" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePremiseConcreteSpec"
        eType="#//File" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceConclusionAbstractSpec"
        eType="#//File" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePremiseAbstractSpec"
        eType="#//File" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetConclusionConcreteSpec"
        eType="#//File" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPremiseConcreteSpec"
        eType="#//File" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetConclusionAbstractSpec"
        eType="#//File" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPremiseAbstractSpec"
        eType="#//File" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="#//File">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publisher" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authors" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionReg" eSuperTypes="#//ModelReg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedModel" eType="#//File"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
